# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  sqlproj: 'src\database\VideoDB\VideoDB.sqlproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  testCatalog: $(db_catalog)_Test

steps:
- task: MSBuild@1
  inputs:
    configuration: $(buildConfiguration)
    solution: $(sqlproj)

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: $(azure_subscription)
    authenticationType: aadAuthenticationPassword
    serverName: $(db_source)
    databaseName: $(testCatalog)
    aadSqlUsername: $(db_username)
    aadSqlPassword: $(db_password)
    deployType: DacpacTask
    deploymentAction: Publish
    dacpacFile: 'src\database\VideoDB\**\*.dacpac'

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: 'src\database\VideoDB.UnitTests\VideoDB.UnitTests.csproj'
    feedsToUse: Select