# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  testConfiguration: 'Debug'
  test_catalog: $(db_catalog)_Test

stages:
- stage: Build_And_Unit_Test
  variables:
    dacpacLocation: 'src\database\VideoDB\bin\Release\VideoDB.dacpac'
  jobs:
  - job: Database
    variables:
      sqlproj: 'src\database\VideoDB\VideoDB.sqlproj'
      dbLocation: src\database
      unitTestName: VideoDB.UnitTests
      unitTestProj: '$(dbLocation)\$(unitTestName)\$(unitTestName).csproj'
      assemblyLocation: $(dbLocation)\$(unitTestName)\bin\Release
    steps:
    - task: MSBuild@1
      inputs:
        configuration: $(buildConfiguration)
        solution: $(sqlproj)
    - task: CopyFiles@2
      inputs:
        contents: $(dacpacLocation)
        targetFolder: $(Build.ArtifactStagingDirectory)\VideoDbDacPac
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: $(azure_subscription)
        authenticationType: aadAuthenticationPassword
        serverName: $(db_source)
        databaseName: $(test_catalog)
        aadSqlUsername: $(db_username)
        aadSqlPassword: $(db_password)
        deployType: DacpacTask
        deploymentAction: Publish
        dacpacFile: $(dacpacLocation) 
    - task: NuGetCommand@2
      inputs:
        command: restore
        restoreSolution: $(unitTestProj)
        feedsToUse: Select
        includeNuGetOrg: true
        restoreDirectory: '$(dbLocation)\$(unitTestName)\packages'
    - task: MSBuild@1
      inputs:
        configuration: $(testConfiguration)
        solution: $(unitTestProj)
    - task: VSTest@2
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: '$(unitTestName).dll'
        searchFolder: $(assemblyLocation)
        configuration: $(testConfiguration)
        overrideTestrunParameters: '-override_connection_string true'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)\VideoDbDacPac
        artifactName: VideoDbDacpac        