# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  sqlproj: '**/*.sqlproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: MSBuild@1
  inputs:
    msbuildVersion: 15.0
    configuration: $(buildConfiguration)
    solution: '**/*.sqlproj'

- task: SqlAzureDacpacDeployment@1
  inputs:
    authenticationType: aadAuthenticationPassword
    serverName: $(db_source)
    databaseName: $(db_catalog)_Test
    aadSqlUsername: $(db_username)
    aadSqlPassword: $(db_password)
    deployType: DacpacTask
    deploymentAction: Publish
    dacpacFile: "database/VideoDB/$(buildConfiguration)/*.dacpac"