# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  testConfiguration: 'Release'
  test_catalog: $(db_catalog)_dev

stages:
- stage: Build_And_Unit_Test
  variables:
    dacpacLocation: 'src\database\VideoDB\bin\$(buildConfiguration)\VideoDB.dacpac'
  jobs:
  - job: Database
    variables:
      sqlproj: 'src\database\VideoDB\VideoDB.sqlproj'
      dbLocation: src\database
      unitTestName: VideoDB.UnitTests
      unitTestProj: '$(dbLocation)\$(unitTestName)\$(unitTestName).csproj'
      assemblyLocation: $(dbLocation)\$(unitTestName)\bin\$(testConfiguration)
    steps:
    - task: MSBuild@1
      inputs:
        configuration: $(buildConfiguration)
        solution: $(sqlproj)
    - task: CopyFiles@2
      inputs:
        contents: $(dacpacLocation)
        targetFolder: $(Build.ArtifactStagingDirectory)\VideoDbDacPac
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: $(azure_subscription)
        authenticationType: aadAuthenticationPassword
        serverName: $(db_source)
        databaseName: $(test_catalog)
        aadSqlUsername: $(db_username)
        aadSqlPassword: $(db_password)
        deployType: DacpacTask
        deploymentAction: Publish
        dacpacFile: $(dacpacLocation) 
    - task: NuGetCommand@2
      inputs:
        command: restore
        restoreSolution: $(unitTestProj)
        feedsToUse: Select
        includeNuGetOrg: true
        restoreDirectory: '$(dbLocation)\$(unitTestName)'
    - task: VSTest@2
      inputs:
        testSelector: testAssemblies
        testAssemblyVer2: '$(unitTestName).dll'
        searchFolder: $(assemblyLocation)
        configuration: $(testConfiguration)
        overrideTestrunParameters: '-override_connection_string true -db_password $(db_password)'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)\VideoDbDacPac
        artifactName: VideoDbDacpac        
  - job: WebApi
    variables:
      apiProjName: 'VideoDB.WebApi'
      unitTestProjName: VideoDB.WebApi.Tests
      apiProjDirectory: 'src\main\$(apiProjName)'
      unitTestDirectory: 'src\test\$(unitTestProjName)'
      solution: 'src\VideoDB.sln'
      apiProject: $(apiProjDirectory)\$(apiProjName).csproj
      unitTestProject: $(unitTestDirectory)\$(unitTestProjName).csproj
      System.Debug: true
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: $(solution)
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: $(unitTestProject)
        arguments: '-c $(testConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: $(unitTestProject)
        arguments: '-c $(testConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: $(apiProject)
        arguments: '-c $(buildConfiguration)'    
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        projects: $(apiProject)
        arguments: '-c $(buildConfiguration)'    
    - task: CopyFiles@2
      inputs:
        contents: '$(apiProjDirectory)\bin\$(buildConfiguration)\netcoreapp3.0\publish.zip'
        targetFolder: $(Build.ArtifactStagingDirectory)\WebApi
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)\WebApi
        artifactName: WebApi   
- stage: Integration_Test
  dependsOn: Build_And_Unit_Test
  variables:
      intTestProjName: VideoDB.WebApi.Tests.Integration
      intTestDirectory: 'src\test\$(intTestProjName)'
      intTestProj: $(intTestDirectory)\$(intTestProjName).csproj
  jobs:
  - job: WebApiIntegrationTest
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: $(intTestProj)
    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: $(intTestProj)
        arguments: '-c $(testConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: $(intTestProj)
        arguments: '-c $(testConfiguration)'